version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=app_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword

  database:
    build: ./db